### ISSUE TITLE
Update would be nice

### ISSUE THREAD

**Issue by Sager89** [norseman99/dbd-randomizer#2]
Would love to see this updated, I use it for my streams all the time and will do whatever it takes to get updated.

**Comment by norseman99** [comment]
Sorry for the late response. I have quitted DBD because of how BHVR manages the game, so my motivation to update it is pretty much non-existing. I won't say never but at the moment, I don't have any plans to do it. Sorry.

**Comment by Sager89** [comment]
What if I give you $50? I’m a twitch streamer and I love the interface of your wheel compared to other ones out there.

**Comment by norseman99** [comment]
I appreciate the offer but it's really not about the money. Time is much more valuable for me at the moment.

It's not that difficult to update with new characters. All you have to do is update [this file](https://github.com/norseman99/dbd-randomizer/blob/master/script/randomizer-data.js) and add the new images to the correct folders. It's just a little time-consuming.

**Comment by Kayleen88** [comment]
Hi Norseman,

I have done the updates for Sager, but cannot upload as I do not have access to upload the files. Please can you grant me access so that I can upload the latest updates?

Regards
Kayleen

**Comment by norseman99** [comment]
> Hi Norseman,
> 
> I have done the updates for Sager, but cannot upload as I do not have access to upload the files. Please can you grant me access so that I can upload the latest updates?
> 
> Regards Kayleen

Hey Kayleen,

I believe you should be able to create a pull request from your fork.

If everything is good, I'll merge it to the main code base.

Cheers

**Comment by Kayleen88** [comment]
Hi,

Created Pull Request :)

**Comment by norseman99** [comment]
Closing this one as the randomizer has been updated with the latest DLCs.
